### ISSUE TITLE
Some characters trigger a stack trace

### ISSUE THREAD

**Issue by ivorycoast** [Greenstand/treetracker-wallet-api#187]
**Explaination:**

When providing a special character, the application returns an HTML response with a stack trace:

`GET /trust_relationships%`

It works with each HTTP verb. Here is the error message I got:

```
HTTP/1.1 400 Bad Request
...
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>URIError: Failed to decode param &#39;/trust_relationships%&#39;<br> &nbsp; &nbsp;at decodeURIComponent (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at decode_param (/.../treetracker-wallet-api/node_modules/express/lib/router/layer.js:172:12)<br> &nbsp; &nbsp;at Layer.match (/.../treetracker-wallet-api/node_modules/express/lib/router/layer.js:123:27)<br> &nbsp; &nbsp;at matchLayer (/.../treetracker-wallet-api/node_modules/express/lib/router/index.js:574:18)<br> &nbsp; &nbsp;at next (/.../treetracker-wallet-api/node_modules/express/lib/router/index.js:220:15)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/.../treetracker-wallet-api/node_modules/express/lib/router/layer.js:91:12)<br> &nbsp; &nbsp;at trim_prefix (/.../treetracker-wallet-api/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /.../treetracker-wallet-api/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/.../treetracker-wallet-api/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/.../treetracker-wallet-api/node_modules/express/lib/router/index.js:275:10)</pre>
</body>
</html>
```

**Risk:**
Back-end Information Disclosure

**Where is the issue?**
For each HTTP request verb

**How to fix/Recommendation:**
I recommend to add this inside your app.js and before each HTTP verb:
```
app.use(function(req, res, next) {
    var err = null;
    try {
        decodeURIComponent(req.path)
    }
    catch(e) {
        err = e;
    }
    if (err){
        < DO SOMETHING / SEND AN ERROR MESSAGE >    
    }
    next();
});
```

**Comment by dadiorchen** [comment]
Yes, this is a valid issue.

**Comment by Kpoke** [comment]
Ambassador already takes care of this for us

https://dev-k8s.treetracker.org/wallet/wallets%

returns

 {
"message": "parse \"/wallet/wallets%\": invalid URL escape \"%\"",
"request_id": "14712432011462190764",
"status_code": 500
}
