### ISSUE TITLE
Protential problem about connecting the DB with Knex.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-api#51]
Maybe we are doing in a wrong way to connect DB by Knex, or didn't release some resource with time.
I met error throwing on a few occasions.

```
(node:10973) UnhandledPromiseRejectionWarning: error: sorry, too many clients already
    at Connection.parseE (/Users/deanchen/work/greenstand/code/treetracker-token-trading-api/node_modules/pg/lib/connection
.js:614:13)
    at Connection.parseMessage (/Users/deanchen/work/greenstand/code/treetracker-token-trading-api/node_modules/pg/lib/conn
ection.js:413:19)
    at Socket.<anonymous> (/Users/deanchen/work/greenstand/code/treetracker-token-trading-api/node_modules/pg/lib/connectio
n.js:129:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
(node:10973) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside
 of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate th
e node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api
/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:10973) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections t
hat are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by deepwinter** [comment]
Is this from running the server or from the integration tests?   I have seen when connecting to a db in command line scripts from node.js I do need to explicitly close the database connection or I get errors like this - you might not be doing this.
